### PR TITLE
Use usvg instead of resvg, minor fixes

### LINKED ISSUE #349: Use usvg instead of resvg in the svg_render example
It's the same underlying code, resvg depends on usvg and we only use the usvg part so let's just depend on that crate instead.

### PR DESCRIPTION
**Pull request by zen3ger**
Typo and zoom control char fixes.
Added option to set msaa from commandline.
Replace resvg with usvg.

Closes #349

### CODE REVIEW

**Comment by zen3ger** [comment]
I saw that the `cli` uses `clap`, I thought it might be an overkill here, but should I use it?

File: examples/svg_render/src/main.rs [hunk 1]
```diff
@@ -240,10 +264,10 @@ fn update_inputs(scene: &mut Scene, event_loop: &mut glutin::EventsLoop) -> bool
                 VirtualKeyCode::Escape => {
                     status = false;
                 }
-                VirtualKeyCode::PageDown => {
```
Comment (nical) [inline examples/svg_render/src/main.rs]: I'd prefer to keep PgUp/down to control the zoom like in the other examples and the cli app.

**Comment by zen3ger** [comment]
Sorry, I saw the `println!()` with sqare brackets and thought it was messed up. I fixed the text and added `clap`. If everything is fine, I'll squash the commits.
